name: App
options:
  bundleIdPrefix: tomasz.korab.App
  deploymentTarget:
  iOS: 15.0
packages:
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    branch: main

targets:

  App:
    type: application
    platform: iOS
    sources:
      - path: Presentation/Code
        createIntermediateGroups: true
      - path: Business/Code
        createIntermediateGroups: true
      - path: Data/Code
        createIntermediateGroups: true
    dependencies:
      - package: ComposableArchitecture

  DataTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Data/Tests
        createIntermediateGroups: true
      - path: Support/Resources
        createIntermediateGroups: true
        buildPhase: resources
      - path: Support/TestsSupport
        createIntermediateGroups: true
        buildPhase: sources
    dependencies:
      - target: App
      
  BusinessTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Business/Tests
        createIntermediateGroups: true
      - path: Support/TestsSupport
        createIntermediateGroups: true
        buildPhase: sources
    dependencies:
      - target: App

schemes:

  AppOnline:
    build:
      targets:
        App: all
    run:
      config: Debug
      
  AppOffline:
    build:
      targets:
        App: all
    run:
      config: Debug
      environmentVariables:
        - variable: RUNNING_TESTS
          value: TRUE
          isEnabled: true

  DataTests:
    build:
      targets:
        DataTests: [test]
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - name: DataTests
          parallelizable: true
          randomExecutionOrder: true
      environmentVariables:
        - variable: RUNNING_TESTS
          value: TRUE
          isEnabled: true

  BusinessTests:
    build:
      targets:
        BusinessTests: [test]
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - name: BusinessTests
          parallelizable: true
          randomExecutionOrder: true
      environmentVariables:
        - variable: RUNNING_TESTS
          value: TRUE
          isEnabled: true

