name: App
options:
  bundleIdPrefix: tomasz.korab.App
  deploymentTarget:
  iOS: 14.0
packages:
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    branch: main

targets:

  App:
    type: application
    platform: iOS
    sources:
      - path: App
    dependencies:
      - target: Engine
        embed: false
      - package: ComposableArchitecture
    settings:
      configs:
        - ENABLE_BITCODE: NO

  Networking:
    type: framework
    platform: iOS
    testTargets:
      - NetworkingTests
    sources:
      - Networking
      - path: Resources
        buildPhase: resources

  NetworkingTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - NetworkingTests
      - path: Resources
        buildPhase: resources
      - path: TestsSupport
        buildPhase: sources
    dependencies:
      - target: Networking

  Engine:
    type: framework
    platform: iOS
    testTargets:
      - EngineTests
    sources:
      - Engine
    dependencies:
      - target: Networking
        embed: false
      
  EngineTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - EngineTests
      - path: TestsSupport
        buildPhase: sources
    dependencies:
      - target: Engine

schemes:

  AppOnline:
    build:
      targets:
        App: all
    run:
      config: Debug
      
  AppOffline:
    build:
      targets:
        App: all
    run:
      config: Debug
      environmentVariables:
        - variable: RUNNING_TESTS
          value: TRUE
          isEnabled: true

  Networking:
    build:
      targets:
        Networking: all
    run:
      config: Debug

  NetworkingTests:
    build:
      targets:
        NetworkingTests: [test]
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - name: NetworkingTests
          parallelizable: true
          randomExecutionOrder: true
      environmentVariables:
        - variable: RUNNING_TESTS
          value: TRUE
          isEnabled: true
          
  Engine:
    build:
      targets:
        Engine: all
    run:
      config: Debug

  EngineTests:
    build:
      targets:
        EngineTests: [test]
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - name: EngineTests
          parallelizable: true
          randomExecutionOrder: true
